---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ta-pv-claim
  labels:
    app: teamcity-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-s3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ta2-pv-claim
  labels:
    app: teamcity-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-s3
---
kind: Deployment
# kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: teamcity-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        name: teamcity-agent
        app: teamcity-agent
    spec:
      containers:
        - name: teamcityagent
          image: studioone/team-agent-node
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SERVER_URL
              value: http://ci.oleobet.com:8111
          volumeMounts:
            # - name:  agent-conf
            #   mountPath: /data/teamcity_agent/conf
            - name: agent-data
              mountPath: /opt/buildAgent
      initContainers:
        # - name: agent-conf-storage-fix
        #   image: busybox
        #   command: ['sh','-c','chmod -R 777 /data/teamcity_agent/conf']
        #   volumeMounts:
        #   - name: agent-conf
        #     mountPath: /data/teamcity_agent/conf
        - name: agent-data-storage-fix
          image: busybox
          command: ['sh','-c','chmod -R 777 /opt/buildAgent']
          volumeMounts:
          - name: agent-data
            mountPath: /opt/buildAgent
      volumes:
        - name: agent-data
          persistentVolumeClaim:
            claimName: ta-pv-claim
        - name: agent-conf
          persistentVolumeClaim:
            claimName: ta2-pv-claim